config/routes.rb
Viewthought::Application.routes.draw do
  root :to => 'pages#home'

  match 'home'         => 'pages#home'
  match 'home_alt'     => 'pages#home_alt'
  match 'case_studies' => 'pages#case_studies'
  match 'contact'      => 'pages#contact'
  match 'government'   => 'pages#government'

  resources :messages, :controller => 'pages'
end

app/models/message.rb
class Message
  include ActiveAttr::Model
  include ActiveAttr::MassAssignment

  attribute :full_name
  attribute :email_address
  attribute :phone_number
  attribute :message

  attr_accessor :full_name, :email_address, :phone_number, :message

  validates_presence_of :full_name, :message => 'What\'s your name?'
  validates_format_of :email_address, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, :message => 'What\'s your email address?'
  validates_length_of :message, maximum: 1000, :message => 'This form is limited to 1000 characters.'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include Mobvious::Rails::Controller
  before_filter :prepare_for_mobile


  private

  def prepare_for_mobile
    if request.env['mobvious.device_type'] == :mobile
      prepend_view_path "app/views/mobile"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @message = Message.new
  end

  def home_alt
    @message = Message.new
  end

  def case_studies
  end

  def government
  end

  def contact
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      ContactMailer.contact_us_message(@message).deliver
      redirect_to home_url(:anchor => "contact-us"), notice: "Got it! Thank you for contacting us."
      # results in this URL: http://localhost:3000/home#contact-us
    else
      render "home"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Mobvious::Rails::Helper

  def device_test
    # Drop in controller: @device = request.env['mobvious.device_type']
    no_device = "What!? That's nil bro."
    if @device.nil?
      no_device
    else
      "#{@device}"
    end
  end

  def head
    render :partial => 'layouts/head'
  end

  def scripts
    render :partial => 'layouts/scripts'
  end

  def chromeframe
    render :partial => 'layouts/chromeframe'
  end

  def nav_tab(title, url, key, options = {})
    current_tab = options.delete(:current)
    # options[:class] = (current_tab == title) ? 'active' : 'inactive'
    klass = (current_tab == title) ? 'active' : 'inactive'
    content_tag(:a, title, :href => url, :accesskey => key, :class => klass)
  end

  def currently_at(tab)
    render partial: 'shared/navigation_text', locals: {current_tab: tab}
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_chromeframe.html.haml
/[if lt IE 7 ]
  .chromeframe
    %p We can support Internet Explorer 6, and have done so many times for our customers over the years. We can do so for your customers if you would like us to, but for this website we have decided not to support Internet Explorer 6 for the following reasons:
    %ol
      %li
        It's use in the United States has declined to less than .2%:
        %a{:href => 'http://www.ie6countdown.com/', :title => ''} The Internet Explorer 6 Countdown
      %li
        Microsoft will end support for Microsoft XP in less than a year, and along with this Internet Explorer 6:
        %a{:href => 'http://www.microsoft.com/en-us/windows/endofsupport.aspx', :title => ''} Windows XP SP3 and Office 2003 Support Ends April 8, 2014
      %li
        It's common practice now to give customers options to upgrade; in a message that only appears in Internet Explorer 6 or older browsers:
        %div.warning
          %p
            Your browser is ancient!
            %a{:href => "http://browsehappy.com/"} Upgrade
            to a different browser
            or activate
            %a{:href => "http://www.google.com/chromeframe/?redirect=true"} Google Chrome Frame
            to experience this website.
      %li Finally, by default, as mobile first developers, our users will experience the mobile version of this site when browsing with Internet Explorer 6. The mobile version is optimized for mobile device limitations, and consequently will work on Internet Explorer 6.

app/views/layouts/_head.html.haml
%head
  %meta{:charset => "utf-8"}
  %link{:rel => "dns-prefetch", :href => "//ajax.googleapis.com"}
  %link{:rel => "dns-prefetch", :href => "//maps.googleapis.com"}
  %link{:rel => "dns-prefetch", :href => "//use.typekit.net"}
  %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
  %title= content_for?(:title) ? ("Ojala, Inc. - " + yield(:title)) : "Ojala, Inc."
  %meta{:name => "viewport", :content => "width=device-width"}

  -# Search Engine Optimization:
  %meta{:name => "description", :content => "Ojala, Inc. provides mobile and web content strategy, design and development services."}
  %meta{:name => "keywords", :content => "Website Design and Development, Mobile, Digital Strategy Consulting, Content Management Systems (CMS), E-Commerce, Site Maintenance and Monitoring, Traffic Analysis, User Statistics, Graphic Design, Branding, Identity, Usability, UX, Information Architecture, Content Creation/Review, Videography, Photography, Search Engine Optimization (SEO), Website Optimization, Integration, Website Hosting and Security,West Palm Beach, Florida"}
  %meta{:prefix => "og: http://ogp.me/ns#", :property => "og:type", :content => "Article"}
  %meta{:prefix => "og: http://ogp.me/ns#", :property => "og:title", :content => "Ojala, Inc."}
  %meta{:prefix => "og: http://ogp.me/ns#", :property => "og:description", :content => "Builders of Mobile and Desktop Web Solutions :: Ojala, Inc. designs well thought out, intuitive online user experiences that look exceptional on any device."}
  %meta{:prefix => "og: http://ogp.me/ns#", :property => "og:url", :content => "http://www.ojalainc.com/"}
  %meta{:prefix => "og: http://ogp.me/ns#", :property => "og:site_name", :content => "Ojala, Inc."}
  %meta{:name => "twitter:card", :content => "summary"}
  %meta{:name => "twitter:site", :content => "@ojala"}
  %meta{:property => "article:published_time", :content => "2013-08-12"}
  %meta{:property => "article:modified_time", :content => "2013-08-14"}

  -# Microsoft tiles:
  -# %meta{:name => "Ojala, Inc.", :content => "#ffffff"}
  -# %meta{:name => "msapplication-square70x70logo", :content => "/tile/tiny.png"}
  -# %meta{:name => "msapplication-square150x150logo", :content => "/tile/square.png"}
  -# %meta{:name => "msapplication-wide310x150logo", :content => "/tile/wide.png"}
  -# %meta{:name => "msapplication-square310x310logo", :content => "/tile/large.png"}

  %link{:rel => "shortcut icon", :href => "/favicon.ico"}
  %link{:rel => "apple-touch-icon", :href => "/apple-touch-icon.png"}

  = stylesheet_link_tag "application"
  = javascript_include_tag 'modernizr.custom.87550'

  :javascript
    (function() {
      var config = {
        kitId: 'lhf6dru',
        scriptTimeout: 2000
      };
      var h=document.getElementsByTagName("html")[0];h.className+=" wf-loading";var t=setTimeout(function(){h.className=h.className.replace(/(\s|^)wf-loading(\s|$)/g," ");h.className+=" wf-inactive"},config.scriptTimeout);var tk=document.createElement("script"),d=false;tk.src='//use.typekit.net/'+config.kitId+'.js';tk.type="text/javascript";tk.async="true";tk.onload=tk.onreadystatechange=function(){var a=this.readyState;if(d||a&&a!="complete"&&a!="loaded")return;d=true;clearTimeout(t);try{Typekit.load(config)}catch(b){}};var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(tk,s)
    })();

  = csrf_meta_tag

app/views/layouts/_scripts.html.haml
= javascript_include_tag "application"
= mobvious_javascript

/[if (IE 7)|(IE 8)]
  %script{:src => "https://s3.amazonaws.com/ojala-inc/assets/respond.min.js", :type => "text/javascript"}
  -# %script{:src => "assets/respond.min.js", :type => "text/javascript"}

/[if (IE 6)|(IE 7)]
  %script{:src => "https://s3.amazonaws.com/ojala-inc/assets/lte-ie7.js", :type => "text/javascript"}
  -# %script{:src => "assets/lte-ie7.js", :type => "text/javascript"}

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47555027-6', 'ojalainc.com');
  ga('send', 'pageview');

app/views/layouts/application.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
:plain
  <!--[if gt IE 8] -->
%html.no-js{:lang => "en"}
  /<![endif]

  = head
  %body
    .wrapper
      = chromeframe
      %header{:role => 'banner', :id => 'home'}
        .container
          = render :partial => 'shared/logo'
          = yield :navigation_text
          =# render :partial => 'shared/navigation_icon'
          =# render :partial => 'shared/social_links'
          = render :partial => 'shared/phone_number'
      #main{:role => 'main'}
        = yield
    = scripts

app/views/mobile/layouts/_head.html.haml
%head
  %meta{:charset => "utf-8"}
  %link{:rel => "dns-prefetch", :href => "//ajax.googleapis.com"}
  %link{:rel => "dns-prefetch", :href => "//maps.googleapis.com"}
  %link{:rel => "dns-prefetch", :href => "//use.typekit.net"}
  %title= content_for?(:title) ? ("Ojala, Inc. - " + yield(:title)) : "Ojala, Inc."

  %meta{:name => "description", :content => "Ojala, Inc. provides mobile and web content strategy, design and development services."}
  %meta{:name => "HandheldFriendly", :content => "True"}
  %meta{:name => "MobileOptimized", :content => "320"}
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
  %meta{"http-equiv" => "cleartype", :content => "on"}

  %link{:rel => "apple-touch-icon-precomposed", :sizes => "144x144", :href => "/apple-touch-icon-144x144-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :sizes => "114x114", :href => "/apple-touch-icon-114x114-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :sizes => "72x72", :href => "/apple-touch-icon-72x72-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :href => "/apple-touch-icon-57x57-precomposed.png"}
  %link{:rel => "shortcut icon", :href => "/apple-touch-icon.png"}

  -# Tile icon for Win8 (144x144 + tile color)
  %meta{:name => "msapplication-TileImage", :content => "/apple-touch-icon-144x144-precomposed.png"}
  %meta{:name => "msapplication-TileColor", :content => "#222222"}

  -# For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94
  -# %meta{:name => "apple-mobile-web-app-capable", :content => "yes"}//
  -# %meta{:name => "apple-mobile-web-app-status-bar-style", :content => "black"}
  -# %meta{:name => "apple-mobile-web-app-title", :content => ""}

  -# This script prevents links from opening in Mobile Safari. https://gist.github.com/1042026
  -# :javascript
  -#   (function(a,b,c){if(c in b&&b[c]){var d,e=a.location,f=/^(a|html)$/i;a.addEventListener("click",function(a){d=a.target;while(!f.test(d.nodeName))d=d.parentNode;"href"in d&&(d.href.indexOf("http")||~d.href.indexOf(e.host))&&(a.preventDefault(),e.href=d.href)},!1)}})(document,window.navigator,"standalone")

  = stylesheet_link_tag "mobile"
  = javascript_include_tag 'modernizr.custom.87550'

  :javascript
    (function() {
      var config = {
        kitId: 'lhf6dru',
        scriptTimeout: 2000
      };
      var h=document.getElementsByTagName("html")[0];h.className+=" wf-loading";var t=setTimeout(function(){h.className=h.className.replace(/(\s|^)wf-loading(\s|$)/g," ");h.className+=" wf-inactive"},config.scriptTimeout);var tk=document.createElement("script"),d=false;tk.src='//use.typekit.net/'+config.kitId+'.js';tk.type="text/javascript";tk.async="true";tk.onload=tk.onreadystatechange=function(){var a=this.readyState;if(d||a&&a!="complete"&&a!="loaded")return;d=true;clearTimeout(t);try{Typekit.load(config)}catch(b){}};var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(tk,s)
    })();

  = csrf_meta_tag

app/views/mobile/layouts/_scripts.html.haml
= javascript_include_tag "mobile"

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47555027-6', 'ojalainc.com');
  ga('send', 'pageview');

app/views/mobile/layouts/application.html.haml
!!!
%html.no-js
  = head
  %body
    .wrapper
      %header{:role => 'banner', :id => 'home'}
        .container
          = render :partial => 'shared/logo'
          = render :partial => 'shared/social_links'
          =# render :partial => 'shared/navigation_icon'
      #main{:role => "main"}
        = yield
    = scripts

app/views/mobile/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/mobile/pages/about.html.haml

app/views/mobile/pages/portfolio.html.haml
%h1 Pages#about
%p Find me in app/views/mobile/pages/about.html.haml

app/views/mobile/pages/privacy.html.haml
%h1 Pages#privacy
%p Find me in app/views/mobile/pages/privacy.html.haml

app/views/mobile/pages/site_map.html.haml
%h1 Pages#site_map
%p Find me in app/views/mobile/pages/site_map.html.haml

app/views/mobile/pages/terms.html.haml
%h1 Pages#terms
%p Find me in app/views/mobile/pages/terms.html.haml

app/views/mobile/shared/_competency_list.html.haml
%ul
  %li Website Design and Development
  %li Digital Strategy Consulting
  %li Mobile Development
  %li Content Management Systems (CMS)
  %li E-commerce
  %li Usability/UX
  %li Information Architecture
  %li Content Creation/Review
  %li Traffic analysis, user statistics
  %li Search Engine Optimization (SEO)
  %li Graphic Design, Branding, Identity
  %li Videography/Photography
  %li Website Optimization
  %li Integration
  %li Site maintenance and monitoring
  %li Website Hosting and Security

app/views/mobile/shared/_navigation.html.haml
%nav{:id => 'nav', :role => 'navigation'}
  %a{:href => "/", :title => 'Home'}
    %span{"aria-hidden" => "true", "data-icon" => "&#xe00c;".html_safe}
    %span.screen-reader-text Home
  %a{:href => "/work", :title => 'Work'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x27;".html_safe}
    %span.screen-reader-text Work
  %a{:href => "/team", :title => 'Team'}
    %span{"aria-hidden" => "true", "data-icon" => "&#xe029;".html_safe}
    %span.screen-reader-text Team
  %a{:href => "/contact", :title => 'Contact'}
    %span{"aria-hidden" => "true", "data-icon" => "&#xe006;".html_safe}
    %span.screen-reader-text Contact
  %a{:href => "/thoughts", :title => 'Thoughts'}
    %span{"aria-hidden" => "true", "data-icon" => "&#xe005;".html_safe}
    %span.screen-reader-text Thoughts
  %a{:href => "/labs", :title => 'Labs'}
    %span{"aria-hidden" => "true", "data-icon" => "l".html_safe}
    %span.screen-reader-text Labs

app/views/pages/_contact_form.html.haml
-# http://stackoverflow.com/questions/2068887/rails-render-action-to-target-anchor-tag
= form_for @message, :url => { :action => "create" , :anchor => "contact-us" } do |f|
  =# form_for @message do |f|
  - if @message.errors.any?
    .error_messages
      %h2 Oops...
      %ul
        -# - @message.errors.full_messages.each do |msg|
        -#   %li= msg
        - @message.errors.each_with_index.each do |msg, i|
          %li= msg[1]
  - flash.each do |name, msg|
    = content_tag :div, msg, id: "flash_#{name}"
  %fieldset
    %p
      %span.infield-label
        = f.label 'full_name'
        = f.text_field :full_name
    %p
      %span.infield-label
        = f.label 'email_address'
        = f.email_field :email_address
    %p
      %span.infield-label
        = f.label 'phone_number'
        = f.phone_field :phone_number
    %p
      %span.infield-label.textarea
        = f.label 'message', 'Tell us a little about your project'
        = f.text_area :message, cols: 5, rows: 5
    %p.button
      %span.infield-label
        %button Send

app/views/pages/_home_content.html.haml
%p Nothing beats the involvement of a well seasoned, front-end developer that understands the semantics of what you're trying to pull off.
// %p We are view thought, builders of mobile and desktop web applications. We specialize in developing well thought out user experiences, and beautiful design.
%button Start A Project
%p 561-320-1117

app/views/pages/case_studies.html.haml
= currently_at 'Case Studies'
- content_for :title do
  Case Studies

%section#case-intro
  .container
    .case-intro
      %p
        Your business has a unique value proposition. Through design and interaction we can help communicate it.
        %span.hide-text Through our unique experience in both web development and business&ndash;help to enhance it.
  %a{:href => '#case-study-1', :title => 'Scroll Down', :class => 'white-white scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25be;".html_safe}
    %span.screen-reader-text Scroll Down

%section#case-study-1
  .container
    .case-study-1
      %h2 Northwest Arctic Borough School District
      %p When the Northwest Arctic Borough School District approached Ojala, Inc. for a website redesign project, they were in the final stages of completing a fourteen million dollar overhaul of the Alaska Technical Center, and the launch of Star of the Northwest Magnet School. They needed new modern websites for both; the technical center’s website was antiquated, and the magnet school did not yet have a website.
      #slidingDiv1
        %p Ojala, Inc. was hired to help the school district craft and tell the story for both:
        %ul
          %li Who they are
          %li What they offer
          %li Who should go there and why
          %li What are the steps necessary to attend
        %p They wanted a site that was visually minimalist, complemented by videos, available on mobile devices, and in terms of look and feel conveyed a sense of sophistication, a modern feel, and something uniform between the two sites while distinct from each other.
        %p Over the course of several months we worked with the district, and together crafted what we all feel are two beautiful works of art that accomplish what we set out to achieve.
      %a.show_hide_2{:href => "#", "data-link" => "#slidingDiv1"}
        Read More
      %span.vertical-pipe
      %a.visit_site{href: 'http://atcstar.com', title: 'ATC and Star Websites', target: '_blank'} Visit Site
  %a{:href => '#case-study-2', :title => 'Scroll Down', :class => 'gray-gray scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25be;".html_safe}
    %span.screen-reader-text Scroll Down

%section#atcstar
  .container
    .atcstar
      = image_tag 'atcstar-900.png', alt: 'ATC/Star Website Screenshots', width: '90%'

%section#case-study-2
  .container
    .case-study-2
      %h2 NANA Development Corporation: Aqqaluk Trust
      %p The stakeholders of Aqqaluk Trust felt that their old website was not serving the full purpose of their mission. They described their old website as feeling scattered, “not fluid”, and incoherent; that it had “lost its purpose.”
      #slidingDiv2
        %p Ojala, Inc. was brought on board to help Aqqaluk Trust re-craft their content, hone in on their message, and re-architect how information would be displayed. Certain questions needed to be answered, like:
        %ul
          %li What is Aqqaluk Trust?
          %li What do they do and why was this important?
          %li Why should people care?
          %li How is its work coming into effect?
        %p Most importantly, the look and feel needed to convey the very special cultural aspects of the region, a sense of excitement, and work on mobile devices – where a large percentage of their audience would access the website.
        %p Working with the trust, we set out to develop a site that would answer all of these questions. A website that told a story – while generating excitement about what Aqqaluk Trust was doing – and invite and encourage participation. The result: a fantastic looking website that we, and all the stakeholders at Aqqaluk Trust, are proud of.
      %a.show_hide_2{:href => "#", "data-link" => "#slidingDiv2"}
        Read More
      %span.vertical-pipe
      %a.visit_site{href: 'http://www.aqqaluktrust.com', title: 'Aqqaluk Trust Website', target: '_blank'} Visit Site
  %a{:href => '#our-goal', :title => 'Scroll Down', :class => 'gray-gray scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25be;".html_safe}
    %span.screen-reader-text Scroll Down

%section#aqqaluktrust
  .container
    .aqqaluktrust
      = image_tag 'case-studies-sprite.png', alt: 'Aqqaluk Trust Website Screenshots', width: '90%'

%section#our-goal
  .container
    .our-goal
      %p Our goal is to add value to the companies we serve. Give us a call or email us to learn more.
      .email-button= render :partial => 'shared/email'
  %a{:href => '#home', :title => 'Scroll Up', :class => 'blue-white scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25b4;".html_safe}
    %span.screen-reader-text Scroll Up

app/views/pages/contact.html.haml
= currently_at 'Contact'
- content_for :title do
  Contact

%section#contact-hero
  .container
    .contact-hero
      %p Our style of web development is kind of like dancing. It's collaborative. Sometimes you lead, sometimes you follow&ndash;without stepping on your partner's toes!
  %a{:href => '#email-us', :title => 'Scroll Down', :class => 'white-white scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25be;".html_safe}
    %span.screen-reader-text Scroll Down

%section#email-us
  .container
    .email-us.contact-email-us
      %p We are also nimble and quickly and gracefully adjust to changing end-user and business needs. We have fun.
      .email-button
        %span Email Us:&nbsp;&nbsp;&nbsp;
        = render :partial => 'shared/email'
  %a{:href => '#contact-intro', :title => 'Scroll Down', :class => 'gray-gray scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25be;".html_safe}
    %span.screen-reader-text Scroll Down

%section#contact-intro
  .container
    .contact-intro
      %p Let's build something amazing! Feel free to call, email, or complete the inquiry form and hit send.
      .contact-info
        = render :partial => 'shared/phone_number'
        = render :partial => 'shared/social_links'
    .contact-form
      = render :partial => 'pages/contact_form'
  %a{:href => '#snail-mail', :title => 'Scroll Down', :class => 'white-white scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25be;".html_safe}
    %span.screen-reader-text Scroll Down

%section#snail-mail
  .container
    .snail-mail
      %p.fn.org
        ViewThought
      .adr
        %p.street-address 400 Hibiscus St.
        %p.extended-address 1st Floor
        %p
          %span.locality> West Palm Beach
          ,
          %span.region Florida
          %span.postal-code 33401
  %a{:href => '#in-person', :title => 'Scroll Down', :class => 'gray-gray scroll autoblur'}
    %span{"aria-hidden" => "true", "data-icon" => "&#x25be;".html_safe}
    %span.screen-reader-text Scroll Down

%section#in-person
  #map
  #map-overlay
    .container
      .map-overlay.contact-map-overlay
        %p Want to meet in person around West Palm Beach, Florida?
    %a{:href => '#home', :title => 'Scroll Up', :class => 'white-white bottom-arrow scroll autoblur'}
      %span{"aria-hidden" => "true", "data-icon" => "&#x25b4;".html_safe}
      %span.screen-reader-text Scroll Up

app/views/shared/_competency_list.html.haml
%ul
  %li.col1 Website Design and Development
  %li.col2 Digital Strategy Consulting
  %li.col3 Mobile Development
  %li.col1 Usability/UX
  %li.col2 Content Management Systems (CMS)
  %li.col3 Information Architecture
  %li.col1 E-commerce
  %li.col2 Content Creation/Review
  %li.col3 Traffic analysis, user statistics
  %li.col1 Search Engine Optimization (SEO)
  %li.col2 Graphic Design, Branding, Identity
  %li.col3 Website Optimization
  %li.col1 Videography/Photography
  %li.col2 Integration
  %li.col3 Site maintenance and monitoring
  %li.col1 Website Hosting and Security

app/views/shared/_email.html.erb
<script type="text/javascript"><!--
var tjkbigk = ['m','c','s','l','a','o','a','a','o','f','e','i','c','l','a','/','l','"','r','a',' ','"','c','l','e','l','"','l','a','h','.','<','i','n','<','=','>',':','c','>','e','o','s','a','m','o','h','.','=','h','c','o','@','l','i','m','t','@',' ','e','l','n','l','a','a','j','o','i','j','m','"','o'];var ipcdcko = [44,63,39,59,45,66,70,38,22,6,51,61,29,12,26,69,47,8,4,58,2,48,65,37,17,25,34,53,24,3,64,0,11,28,68,7,49,15,36,71,43,14,40,1,67,54,50,30,41,16,31,32,21,19,27,33,13,55,35,5,52,62,18,10,60,57,56,46,23,9,42,20];var xpyrvnk= new Array();for(var i=0;i<ipcdcko.length;i++){xpyrvnk[ipcdcko[i]] = tjkbigk[i]; }for(var i=0;i<xpyrvnk.length;i++){document.write(xpyrvnk[i]);}
// --></script>
<noscript>Please enable Javascript<br>to see the email address</noscript>

app/views/shared/_navigation.html.haml
%nav{:id => 'nav', :role => 'navigation'}
  = link_to 'Home', home_path, :title => 'Home'
  = link_to 'Work', work_path, :title => 'Work'
  = link_to 'Team', team_path, :title => 'Team'
  = link_to 'Contact', contact_path, :title => 'Contact'
  = link_to 'Thoughts', thoughts_path, :title => 'Thoughts'
  = link_to 'Labs', labs_path, :title => 'Labs'

app/views/shared/_navigation_text.html.haml
- content_for :navigation_text do
  %nav{:id => 'nav', :role => 'navigation'}
    = nav_tab 'Home', home_path, 'h', current: current_tab
    = nav_tab 'Case Studies', case_studies_path, 'w', current: current_tab
    = nav_tab 'Government', government_path, 'g', current: current_tab
    = nav_tab 'Contact', contact_path, 'c', current: current_tab